name = "server"
main = "src/index.ts"
compatibility_date = "2024-12-15"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "KV"
id = "a482d5b1ec9a4e9e8b5446c7dec550d3"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "b2a2b582a2074f90bb9f286a10a12fd9"
